Fix moc error due to Q_ENUMS being used in a namespace, with Qt branch 5.8
Qt > 5.8-alpha1 requires Q_NAMESPACE being added to the namespace, otherwise
this happens:
networkmanager-qt/src/manager.h:44: Error: Namespace declaration lacks Q_NAMESPACE macro.

CCMAIL: bogdan@kde.org